#Requires -Version 5.1
<#
    .SYNOPSIS
        Delete every trace komorebi + whkd left behind.

    .DESCRIPTION
        Removes, in order:
          1. leftover processes
          2. install directories
          3. config files (komorebi.json, whkdrc, applications.json,
             komorebi-resize.json, toggle-transparency.ps1)
          4. state + logs (%LOCALAPPDATA%\komorebi, %LOCALAPPDATA%\whkd)
          5. the compiled helper binaries (%USERPROFILE%\bin\komorebi-*.exe)
          6. PATH entries pointing at those helpers
          7. the YASB widget configs referencing komorebi are NOT touched -
             remove those yourself from config.yaml if you uninstall YASB too.

        A timestamped safety copy of the config files is written next to this
        script first, so this is one step recoverable.

    .NOTES
        Reversible?  Only from the safety copy this script writes. Destructive.
#>
[CmdletBinding()]
param(
    [switch] $Force,

    # What to remove. Default keeps the original behaviour (komorebi + whkd).
    #   all               komorebi + whkd + YASB + AutoHotkey
    #   komorebi-whkd     komorebi + whkd only
    #   yasb              YASB only
    #   autohotkey        AutoHotkey v1 + v2 only
    [ValidateSet('all', 'komorebi-whkd', 'yasb', 'autohotkey')]
    [string] $Scope = 'komorebi-whkd'
)

$ErrorActionPreference = 'Continue'
$Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$Here   = $PSScriptRoot
$Safety = Join-Path $Here "cleanup-safety-$Stamp"

function Say($msg, $color = 'Gray') { Write-Host $msg -ForegroundColor $color }

# Config files per scope. The AutoHotkey startup launcher (AppRunner.vbs) lives
# in the Startup folder and is regenerated by the installer, so the autohotkey
# scope removes that too.
$ConfigFiles = switch ($Scope) {
    'all'             { @(
        "$env:USERPROFILE\komorebi.json",
        "$env:USERPROFILE\.config\whkdrc",
        "$env:USERPROFILE\applications.json",
        "$env:USERPROFILE\.config\komorebi-resize.json",
        "$env:USERPROFILE\.config\toggle-transparency.ps1",
        "$env:USERPROFILE\.config\restart-whkd.cmd",
        "$env:USERPROFILE\.config\komorebi-watchdog.cs",
        "$env:USERPROFILE\.config\yasb\config.yaml",
        "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\AppRunner.vbs"
    ) }
    'komorebi-whkd'   { @(
        "$env:USERPROFILE\komorebi.json",
        "$env:USERPROFILE\.config\whkdrc",
        "$env:USERPROFILE\applications.json",
        "$env:USERPROFILE\.config\komorebi-resize.json",
        "$env:USERPROFILE\.config\toggle-transparency.ps1",
        "$env:USERPROFILE\.config\restart-whkd.cmd",
        "$env:USERPROFILE\.config\komorebi-watchdog.cs"
    ) }
    'yasb'            { @("$env:USERPROFILE\.config\yasb\config.yaml") }
    'autohotkey'      { @("$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\AppRunner.vbs") }
}

# Install directories per scope.
$InstallDirs = switch ($Scope) {
    'all'             { @('C:\Program Files\komorebi', 'C:\Program Files\whkd', 'C:\Program Files\YASB', 'C:\Program Files\AutoHotkey') }
    'komorebi-whkd'   { @('C:\Program Files\komorebi', 'C:\Program Files\whkd') }
    'yasb'            { @('C:\Program Files\YASB') }
    'autohotkey'      { @('C:\Program Files\AutoHotkey') }
}
$StateDirs = switch ($Scope) {
    'all'             { @("$env:LOCALAPPDATA\komorebi", "$env:LOCALAPPDATA\whkd", "$env:LOCALAPPDATA\YASB") }
    'komorebi-whkd'   { @("$env:LOCALAPPDATA\komorebi", "$env:LOCALAPPDATA\whkd") }
    'yasb'            { @("$env:LOCALAPPDATA\YASB") }
    'autohotkey'      { @() }
}
$ProcNames = switch ($Scope) {
    'all'             { @('komorebi', 'whkd', 'komorebi-bar', 'yasb', 'yasbc', 'AutoHotkey', 'AutoHotkey64') }
    'komorebi-whkd'   { @('komorebi', 'whkd', 'komorebi-bar') }
    'yasb'            { @('yasb', 'yasbc') }
    'autohotkey'      { @('AutoHotkey', 'AutoHotkey64') }
}

if (-not $Force) {
    Say ''
    Say 'This permanently deletes all komorebi / whkd config, state and helpers.' 'Yellow'
    Say 'A safety copy of your config files is written next to this script first.' 'Yellow'
    Say ''
    $a = Read-Host 'Type DELETE to continue'
    if ($a -ne 'DELETE') { Say 'aborted, nothing changed' 'Cyan'; exit 0 }
}

Say ''
Say '=== 1/6  safety copy of config files ===' 'Cyan'
if (-not (Test-Path $Safety)) { New-Item -ItemType Directory -Path $Safety -Force | Out-Null }
$copied = 0
foreach ($f in $ConfigFiles) {
    if (Test-Path $f) {
        Copy-Item $f (Join-Path $Safety (Split-Path $f -Leaf)) -Force
        Say "  kept a copy of $(Split-Path $f -Leaf)" 'DarkGray'
        $copied++
    }
}
Say "  safety copy: $Safety ($copied file(s))" 'Green'

Say ''
Say '=== 2/6  leftover processes ===' 'Cyan'
$procs = Get-Process -Name $ProcNames -ErrorAction SilentlyContinue
if ($procs) { $procs | Stop-Process -Force -ErrorAction SilentlyContinue; Say '  killed leftovers' 'Yellow' }
else { Say '  none running' 'DarkGray' }

Say ''
Say '=== 3/6  install directories ===' 'Cyan'
foreach ($d in ($InstallDirs + $StateDirs)) {
    if (Test-Path $d) { Remove-Item $d -Recurse -Force -ErrorAction SilentlyContinue; Say "  removed $d" 'Yellow' }
    else { Say "  not present: $d" 'DarkGray' }
}

Say ''
Say '=== 4/6  config files ===' 'Cyan'
foreach ($f in $ConfigFiles) {
    if (Test-Path $f) { Remove-Item $f -Force -ErrorAction SilentlyContinue; Say "  removed $f" 'Yellow' }
    else { Say "  not present: $(Split-Path $f -Leaf)" 'DarkGray' }
}

Say ''
Say '=== 5/6  compiled helper binaries ===' 'Cyan'
$binDir = Join-Path $env:USERPROFILE 'bin'
# komorebi-watchdog.exe is the LIVE scheduled-task launcher — remove it too.
$helpers = @('komorebi-runner.exe','komorebi-runner.cs','komorebi-watchdog.exe','komorebi-watchdog.cs')
foreach ($h in $helpers) {
    $p = Join-Path $binDir $h
    if (Test-Path $p) { Remove-Item $p -Force -ErrorAction SilentlyContinue; Say "  removed $h" 'Yellow' }
}
# leave %USERPROFILE%\bin alone if it still holds other tools
if ((Test-Path $binDir) -and -not (Get-ChildItem $binDir -ErrorAction SilentlyContinue)) {
    Remove-Item $binDir -Force -ErrorAction SilentlyContinue
    Say "  removed empty $binDir" 'DarkGray'
}

Say ''
Say '=== 6/6  PATH cleanup ===' 'Cyan'
# Only %USERPROFILE%\bin is one we may have added (for the compiled helpers).
# Remove it only when it exists solely for those helpers.
$binDir = Join-Path $env:USERPROFILE 'bin'
$binStillUsed = Test-Path (Join-Path $binDir 'komorebi-runner.exe')
foreach ($scope in 'User','Machine') {
    $cur = [Environment]::GetEnvironmentVariable('Path', $scope)
    if (-not $cur) { continue }
    $parts = @($cur -split ';' | Where-Object { $_.Trim() })
    $kept  = @($parts | Where-Object {
        # drop any path segment that mentions komorebi, and drop %USERPROFILE%\bin
        # only while our helpers are gone from it
        ($_ -notmatch 'komorebi') -and
        (-not ($_ -eq $binDir) -or $binStillUsed)
    })
    if ($kept.Count -ne $parts.Count) {
        [Environment]::SetEnvironmentVariable('Path', ($kept -join ';'), $scope)
        Say "  $scope PATH: removed $($parts.Count - $kept.Count) entr(y/ies)" 'Yellow'
    } else {
        Say "  $scope PATH: clean" 'DarkGray'
    }
}

Say ''
Say '=== verify ===' 'Cyan'
$still = @()
foreach ($f in $ConfigFiles) { if (Test-Path $f) { $still += $f } }
foreach ($d in $InstallDirs) { if (Test-Path $d) { $still += $d } }
if ($still) {
    Say '  still present (locked or in use - reboot and re-run):' 'Yellow'
    $still | ForEach-Object { Say "     $_" 'Yellow' }
} else {
    Say "  clean - no $Scope traces left" 'Green'
}
Say ''
Say "DONE. Config safety copy is at: $Safety" 'Cyan'
Say ''
